# Generated by Django 5.0.1 on 2024-02-15 16:15

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0003_alter_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
